'use strict';
const ErrorCenter=(()=>{
 const stages={safety_policy:'网关安全拦截',authentication:'鉴权',body_encoding:'请求编码',body_read:'读取请求体',json_parse:'JSON 解析',ingress_validation:'接入校验',admission:'准入与排队',queue_or_prepare:'排队与准备',upstream_transport:'上游连接',upstream_response:'上游响应',process:'进程中断'};
 const codes={session_safety_blocked:'会话已因上游安全拒绝而拦截',memory_limit:'内存预算不足',request_too_large:'请求体过大',upstream_invalid_request:'上游拒绝参数或上下文',upstream_not_found:'上游接口或模型不存在',upstream_error:'上游执行失败',upstream_content_policy_violation:'上游内容策略拒绝',upstream_idle_timeout:'上游响应超时',upstream_headers_timeout:'上游响应头超时',upstream_rate_limited:'上游限流',upstream_quota_exhausted:'上游额度耗尽',oauth_invalid:'账户授权失效',invalid_api_key:'网关 Key 无效',invalid_request:'请求格式无效',client_cancelled:'客户端断开',process_interrupted:'进程退出中断请求',stream_interrupted:'上游流中断',queue_timeout:'排队超时',gateway_shutdown:'网关关闭'};
 const causes={cybersecurity_risk:'网络安全风险拦截',content_policy_violation:'内容安全策略拦截',upstream_overloaded:'上游服务过载',invalid_encrypted_tool_output:'加密工具输出无效',unsupported_parameter:'不支持参数',invalid_encrypted_content:'加密上下文无效',context_length_exceeded:'上下文超限',rate_limit_exceeded:'上游限流'};
 function cause(f){if(!f)return '';return [causes[f.reason]||f.reason||f.code,f.param].filter(Boolean).join(' · ');}
 function stage(s){return stages[s]||s||'未知阶段';}
 function title(code){return codes[code]||label(code);}
 function datetimeLocal(value){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
 function range(){return state.errorRange||'24h';}
 function windowFor(){
  if(state.errorWindow)return state.errorWindow;
  const f=state.errorFilter||{},to=range()==='custom'?new Date(f.to):new Date(),from=range()==='custom'?new Date(f.from):new Date(to-({'1h':1,'24h':24,'7d':168}[range()]||24)*3600000);
  return state.errorWindow={from:from.toISOString(),to:to.toISOString()};
 }
 function clearGroup(){state.errorGroup=null;state.errorOffset=0;}
 function refresh(){state.errorWindow=null;state.errorOffset=0;}
 function groupParams(g){return {code:g.code,stage:g.stage,cause:g.cause||'',param:g.param||'',...(g.upstream_status==null?{upstream_missing:'true'}:{upstream_status:g.upstream_status})};}
 function status(r){return r.upstream_status==null?'未收到上游响应':`${r.upstream_status}${r.upstream_status>=200&&r.upstream_status<300?' · 请求失败':''}`;}
 function trend(d){
  const bucket=(d.bucket_seconds||3600)*1000,from=Date.parse(d.from),to=Date.parse(d.to),start=Math.floor(from/bucket)*bucket,counts=new Map(d.trend.map(p=>[Date.parse(p.at),Number(p.count)]));
  const bars=[];for(let at=start;at<to;at+=bucket)bars.push({at,count:counts.get(at)||0});
  const max=Math.max(1,...bars.map(p=>p.count)),width=960/bars.length;
  return `<section class="panel error-trend"><div class="panel-head"><div><h2>错误发生趋势</h2><p>按请求开始时间 · 每${bucket===300000?' 5 分钟':bucket===3600000?'小时':'天'}汇总</p></div><span class="muted">峰值 ${n(max===1&&!d.summary.total?0:max)} 次</span></div><div class="error-chart"><svg viewBox="0 0 960 86" preserveAspectRatio="none" role="img" aria-label="当前筛选范围的错误次数趋势">${bars.map((p,i)=>`<rect x="${i*width+1}" y="${82-p.count/max*70}" width="${Math.max(1,width-3)}" height="${Math.max(1,p.count/max*70)}" rx="2" class="${p.count?'':'empty-bar'}"><title>${esc(dt(p.at)+' · '+n(p.count)+' 次')}</title></rect>`).join('')}</svg></div><div class="chart-labels"><span>${dt(d.from)}</span><span>${dt(d.to)} · 刷新可更新范围</span></div></section>`;
 }
 function options(items,selected,all){return `<option value="">${all}</option>`+items.map(x=>`<option value="${esc(x.id)}" ${selected===x.id?'selected':''}>${esc(x.name||short(x.id))}</option>`).join('');}
 async function page(read){
  const f=state.errorFilter||{},w=windowFor(),query=new URLSearchParams({...f,...w,...(state.errorGroup?groupParams(state.errorGroup):{}),limit:25,offset:state.errorOffset||0});
  const d=await read('/request-errors?'+query),s=d.summary,selected=state.errorGroup;
  const filters=`<form class="error-filters" data-form="error-filter"><div class="error-filter-main"><label>时间范围<select name="range" data-error-range>${[['1h','最近 1 小时'],['24h','最近 24 小时'],['7d','最近 7 天'],['custom','自定义时间']].map(([v,t])=>`<option value="${v}" ${range()===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="error-search">搜索错误<input name="q" value="${esc(f.q)}" placeholder="错误码、原因、参数或请求 ID"></label><label>账户<select name="account_id">${options(d.options.accounts,f.account_id,'全部账户')}</select></label><label>模型<input name="model" value="${esc(f.model)}" placeholder="完整模型名称"></label><button class="primary" type="submit">筛选</button><button class="ghost" type="button" data-action="errors-reset">重置</button></div><div class="error-custom-range" ${range()==='custom'?'':'hidden'}><label>开始时间<input type="datetime-local" name="from" value="${datetimeLocal(w.from)}"></label><label>结束时间<input type="datetime-local" name="to" value="${datetimeLocal(w.to)}"></label><span class="muted">最多 31 天</span></div><details class="error-filter-more" ${['code','stage','upstream_status','key_id','session_id','state','kind'].some(k=>f[k])?'open':''}><summary>更多筛选</summary><div class="error-filter-main"><label>错误码<input name="code" value="${esc(f.code)}" placeholder="例如 memory_limit"></label><label>失败阶段<select name="stage"><option value="">全部阶段</option>${Object.entries(stages).map(([v,t])=>`<option value="${v}" ${f.stage===v?'selected':''}>${t}</option>`).join('')}</select></label><label>上游 HTTP<input type="number" min="100" max="599" name="upstream_status" value="${esc(f.upstream_status)}" placeholder="例如 400"></label><label>接口<select name="kind"><option value="">全部接口</option>${['responses','compact','search'].map(v=>`<option value="${v}" ${f.kind===v?'selected':''}>${v}</option>`).join('')}</select></label><label>状态<select name="state"><option value="">失败 / 拒绝 / 中断</option>${['failed','rejected','interrupted','cancelled'].map(v=>`<option value="${v}" ${f.state===v?'selected':''}>${label(v)}</option>`).join('')}</select></label><label>网关 Key<select name="key_id">${options(d.options.keys,f.key_id,'全部 Key')}</select></label><label>会话 ID<input name="session_id" value="${esc(f.session_id)}" placeholder="完整会话 ID"></label></div></details></form>`;
  const metrics=`<section class="metrics error-metrics"><div class="metric"><label>${f.state==='cancelled'?'取消请求':'错误请求'}</label><strong>${n(s.total)}</strong><small>当前筛选范围 · 跨全部分页</small></div><div class="metric"><label>错误类型</label><strong>${n(s.groups)}</strong><small>按错误码、阶段、上游状态与原因归类</small></div><div class="metric"><label>影响账户 / 会话</label><strong>${n(s.accounts)} <span class="muted">/ ${n(s.sessions)}</span></strong><small>未分配账户、无会话的请求不计入</small></div><div class="metric"><label>最近发生</label><strong class="error-last-seen">${s.last_seen?dt(s.last_seen):'—'}</strong><small>默认不包含客户端取消</small></div></section>`;
  const groups=d.groups.map(g=>`<tr><td><button class="error-group-link ghost" data-action="errors-group" data-group="${esc(JSON.stringify(g))}"><strong>${esc(title(g.code))}</strong><code>${esc(g.code)}</code>${cause({reason:g.cause,param:g.param})?`<span>${esc(cause({reason:g.cause,param:g.param}))}</span>`:''}</button></td><td>${esc(stage(g.stage))}<div class="sub">${esc(status(g))}</div></td><td><strong>${n(g.count)}</strong></td><td>${n(g.accounts)} / ${n(g.sessions)}</td><td>${dt(g.last_seen)}<div class="sub">首次 ${dt(g.first_seen)}</div></td></tr>`);
  const rows=d.items.map(r=>`<tr><td><time>${dt(r.created_at)}</time><div><button class="trace-request-id ghost" data-action="request-detail" data-id="${esc(r.id)}" title="${esc(r.id)}">${icon('requests')}${short(r.id)}${icon('arrow')}</button></div>${tag(r.state)}</td><td class="error-message"><strong>${esc(cause({code:r.upstream_code,reason:r.cause,param:r.param})||title(r.code))}</strong><code>${esc(r.code)}</code><p>${esc(r.message||'未记录详细说明')}</p></td><td>${esc(stage(r.stage))}<div class="sub">上游 ${esc(status(r))}</div>${r.gateway_status?`<div class="sub">网关错误状态 ${esc(r.gateway_status)}</div>`:''}</td><td><strong class="mono">${esc(r.model||'尚未解析模型')}</strong><div class="sub">${esc(r.account_name||(r.account_id?short(r.account_id):'未分配账户'))}</div><div class="sub">Key · ${esc(r.key_name||(r.key_id==='00000000-0000-0000-0000-000000000000'?'未鉴权':short(r.key_id)))}</div><small>${esc(r.kind)}</small></td><td>${ms(r.total_ms)}<div class="sub">${r.body_bytes==null?'—':(r.body_bytes/1048576).toFixed(2)+' MiB'} · 上游 ${n(r.upstream_attempts)} 次</div>${r.session_id?`<button class="small ghost" data-action="request-session" data-session="${esc(r.session_id)}" data-key="${esc(r.key_id)}">此会话 ${icon('arrow')}</button>`:''}</td></tr>`);
  return head('错误调查','按类型汇总错误，追查到具体调用。')+filters+(selected?`<div class="notice error-selection"><span>当前类型：${esc(title(selected.code))} · ${esc(stage(selected.stage))} · ${esc(status(selected))}${selected.param?' · '+esc(selected.param):''}</span><button class="small ghost" data-action="errors-clear-group">清除类型筛选 ${icon('close')}</button></div>`:'')+metrics+trend(d)+`<section class="panel error-groups"><div class="panel-head"><div><h2>错误类型</h2><p>点击类型筛选下方记录${s.groups>20?' · 显示次数最多的 20 类，共 '+n(s.groups)+' 类；可搜索错误码继续缩小范围':''}</p></div></div>${groups.length?table(['错误与原因','失败位置','次数','账户 / 会话','最近发生'],groups):empty('这个范围没有错误','调整时间范围，或刷新查看最新结果。')}</section><section class="panel error-requests"><div class="panel-head"><h2>错误请求</h2><span class="muted">${n(s.total)} 条 · 最新在前 · 点击 ID 查看详情</span></div>${rows.length?table(['请求','错误原因','失败位置','模型与账户','耗时与请求体'],rows):empty('没有匹配的记录','可清除类型筛选或调整条件。')}</section><div class="pagination"><span>第 ${Math.floor((state.errorOffset||0)/25)+1} 页 · 共 ${n(s.total)} 条</span><div><button class="small" data-action="errors-prev" ${!state.errorOffset?'disabled':''}>上一页</button><button class="small" data-action="errors-next" ${(state.errorOffset||0)+25>=s.total?'disabled':''}>下一页</button></div></div><p class="muted error-retention-note">范围按请求开始时间计算，仅包含仍保留的请求明细。历史错误可能只有通用描述；新请求可记录已识别的上游原因及参数，不保存请求内容或上游错误原文。</p>`;
 }
 function submit(v){
  const f={};for(const k of ['q','account_id','model','code','stage','upstream_status','kind','state','key_id','session_id'])if(v[k]?.trim())f[k]=v[k].trim();
  if(v.range==='custom'){
   const from=new Date(v.from),to=new Date(v.to);if(!Number.isFinite(+from)||!Number.isFinite(+to)||from>=to||to-from>31*86400000)throw new Error('请选择有效的开始与结束时间，范围不超过 31 天。');
   f.from=from.toISOString();f.to=to.toISOString();
  }
  state.errorFilter=f;state.errorRange=v.range;clearGroup();refresh();return render();
 }
 function action(a,el){
  if(a==='errors-group'){state.errorGroup=JSON.parse(el.dataset.group);state.errorOffset=0;}
  if(a==='errors-clear-group')clearGroup();
  if(a==='errors-reset'){state.errorFilter={};state.errorRange='24h';clearGroup();refresh();}
  if(a==='errors-prev'||a==='errors-next')state.errorOffset=Math.max(0,(state.errorOffset||0)+(a==='errors-next'?25:-25));
  if(a==='errors-related'){close();const at=new Date(el.dataset.at);state.errorFilter={code:el.dataset.code,from:new Date(at-3600000).toISOString(),to:new Date(+at+23*3600000).toISOString()};state.errorRange='custom';clearGroup();refresh();return navigate('errors');}
  return render();
 }
 return {page,submit,action,refresh,cause};
})();
document.addEventListener('change',e=>{if(e.target.matches('[data-error-range]'))e.target.form.querySelector('.error-custom-range').hidden=e.target.value!=='custom';});
